dating_libre_app:
    site_name: 'Dating Libre'
    site_description: 'Description of the site'
    admin_email: '"Dating Libre Staging" <admin@example.com>'
    images_bucket: dlibreim
    image_upload: true
    is_demo: false
    payment_providers:
        datinglibre:
            url: https://datinglibre.com
            active: true
    # the values below are limited to alphanumeric characters
    # separated by an underscore. They are used in behat tests
    # and as translation keys. Ansible will generate and run
    # SQL to automatically add them to the database.
    categories:
    - color
    - shape
    attributes:
        color:
        - blue
        - green
        - yellow
        shape:
        - square
        - circle
        - triangle
    interests:
    - north
    - south
    - east
    - west
    rules:
    - spam
    - abusive_messages
    - offsite_linking
    testing_user_email_addresses:
    - admin@datinglibre.com

